name: palm_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build_runner: ^2.4.5
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
