// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdCOA0tRZy_mEgYz0IJ59qUm9aGPfuFl4',
    appId: '1:762582811401:web:1943bb877d836dfa7f49d8',
    messagingSenderId: '762582811401',
    projectId: 'palm-api-sample',
    authDomain: 'palm-api-sample.firebaseapp.com',
    storageBucket: 'palm-api-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWoyjNlVRvBwbq3_jxljV8XTtTKLLNXk',
    appId: '1:762582811401:android:423d7bb2fbbdc24e7f49d8',
    messagingSenderId: '762582811401',
    projectId: 'palm-api-sample',
    storageBucket: 'palm-api-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD08u9E-n6l0ThzMJaMdMQ99RMyfiwDVmw',
    appId: '1:762582811401:ios:d6dcad3707ae239e7f49d8',
    messagingSenderId: '762582811401',
    projectId: 'palm-api-sample',
    storageBucket: 'palm-api-sample.appspot.com',
    iosClientId: '762582811401-aa2rq5raqopj4r7hqtpkch4echqjmra0.apps.googleusercontent.com',
    iosBundleId: 'com.example.palmSample',
  );
}
